### ISSUE TITLE
Integrate ads API

### ISSUE THREAD

**Issue by vinceengo** [gti525/h17-mobile-billets#12]

**Comment by Kavignon** [comment]
Il y a presentement un bug avec l'API de l'équipe Analutics. Ils prennent pour acquis que nous avons un callback URL alors que nous déployons notre application sur un device Android sans de callback URL. 
Par contre, ce lien a l'air prometteur : http://stackoverflow.com/questions/37366838/handling-redirect-uri-in-ionic-for-external-api
